name: Continuous testing

on:
  pull_request:
    types: [
      'opened',
      'synchronize'
    ]
  push:
    branches:
      - main

jobs:
  test-server:
    name: Server test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
  test-client:
    name: Client test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm --prefix client ci
      - name: check
        run: npm run --prefix client check
      - name: build
        run: npm run --prefix client build
