name: Valist Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v1
      - name: Use node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - uses: valist-io/valist-github-action@v2.3.1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          path: 'client/dist'
          account: javyer
          project: inteplanetary-box
          release: 0.0.4
